### ISSUE TITLE
Add toggle on UI to show/hide annotations

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/Sharktopoda#47]
> Box needed to toggle localization boxes on/off on either the sharktopoda-2 interface or the VARS Annotation interface to clear the image of boxes so it’s easier to identify animals, lines from boxes will sometimes cover other animals we are trying to ID (LL, KRW)

This setting is currently in preferences. But the video lab would like it somewhere on the UI to quickly allow toggling on off while they are annotating. 

This is an enhancement not in the original spec. Should be done under new contract.

**Comment by dingosky** [comment]
To further flesh out this request, the following is a combination of my understanding and my suggestions. Please comment accordingly:

- The current setting in Preferences has global scope, i.e., that setting currently affects all current and future video windows
- It is desired to have to have per video window scope setting
- The setting  in Preferences will remain; however, rather than global scope that setting will be the initial value assigned per new video window, so a change to the Pref setting will affect future opened windows but will no longer affect current open windows
- Any change to a current open video window setting only affects that window
- The per window toggle component will be in the "video control panel", which resides at the bottom of a video window
- The component will be styled exactly like the Pref component, and will be aligned horizontally to the far left margin and vertically in line with the current reverse/pause/play buttons
